providers = ["python"]

[phases.setup]
aptPkgs = []

[phases.install]
cmds = ["python3 -m pip install --prefer-binary --no-compile -r requirements.txt"]
cacheDirectories = ["/root/.cache/pip"]

[start]
cmd = "python3 api_server.py"
